### PR TITLE
Fix typos, reformat sentences and fix badges.

### PR DESCRIPTION
**Pull request by Im-Kal**
Hello,

I have fixed typos, reformatted sentences to make more sense and made the badges center and in a better position.

### CODE REVIEW

**Comment by asger-finding** [comment]
While I appreciate the gesture (no, really, it's awesome to have pull request) the readme is very much still a work-in-progress and is subject to change. I favor more towards the existing layout, and as such I'm closing this.  
Please, feel free to open an issue to discuss something beforehand, so you won't waste time on it. I would especially love code PRs (but again, clear it with me beforehand so the work isn't for nothing) so feel free to contribute in that department.

**Comment by Im-Kal** [comment]
Hi asger,

I completely understand. I do recommend that you would fix the typos which I have provided in the pull request though. If you want, I can file another PR for ONLY the typos.

**Comment by Im-Kal** [comment]
image

**Comment by asger-finding** [comment]
Homebrew is not a typo, though I have added a dash between home and brew. I have already resolved the "being built" typo.

**Pull request closed without merging**
